CREATE TABLE IF NOT EXISTS players(id TEXT PRIMARY KEY,name TEXT NOT NULL,lname TEXT NOT NULL UNIQUE,th TEXT NOT NULL,tr INTEGER NOT NULL DEFAULT 0,lv INTEGER NOT NULL DEFAULT 1,deck TEXT NOT NULL DEFAULT '[]',fort TEXT NOT NULL DEFAULT '[]',al TEXT,ts INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS alliances(id TEXT PRIMARY KEY,name TEXT NOT NULL,lname TEXT NOT NULL UNIQUE,owner TEXT,ts INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS msgs(id INTEGER PRIMARY KEY AUTOINCREMENT,al TEXT NOT NULL,pid TEXT NOT NULL,t TEXT NOT NULL,ts INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS friends(a TEXT NOT NULL,b TEXT NOT NULL,PRIMARY KEY(a,b));
CREATE INDEX IF NOT EXISTS i_tr ON players(tr);
CREATE INDEX IF NOT EXISTS i_msgs ON msgs(al,id);
CREATE INDEX IF NOT EXISTS i_al ON players(al);

-- v2: Karten spenden, Geschenke, Spende-Limit
CREATE TABLE IF NOT EXISTS reqs(id INTEGER PRIMARY KEY AUTOINCREMENT, al TEXT NOT NULL, pid TEXT NOT NULL, card TEXT NOT NULL, need INTEGER NOT NULL, got INTEGER NOT NULL DEFAULT 0, ts INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS reqs_al ON reqs(al, ts);
CREATE TABLE IF NOT EXISTS gifts(id INTEGER PRIMARY KEY AUTOINCREMENT, pid TEXT NOT NULL, card TEXT NOT NULL, n INTEGER NOT NULL, src TEXT, ts INTEGER NOT NULL, done INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS gifts_pid ON gifts(pid, done);
CREATE TABLE IF NOT EXISTS dons(pid TEXT NOT NULL, ts INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS dons_pid ON dons(pid, ts);
