CREATE TABLE IF NOT EXISTS players(id TEXT PRIMARY KEY,name TEXT NOT NULL,lname TEXT NOT NULL UNIQUE,th TEXT NOT NULL,tr INTEGER NOT NULL DEFAULT 0,lv INTEGER NOT NULL DEFAULT 1,deck TEXT NOT NULL DEFAULT '[]',fort TEXT NOT NULL DEFAULT '[]',al TEXT,ts INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS alliances(id TEXT PRIMARY KEY,name TEXT NOT NULL,lname TEXT NOT NULL UNIQUE,owner TEXT,ts INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS msgs(id INTEGER PRIMARY KEY AUTOINCREMENT,al TEXT NOT NULL,pid TEXT NOT NULL,t TEXT NOT NULL,ts INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS friends(a TEXT NOT NULL,b TEXT NOT NULL,PRIMARY KEY(a,b));
CREATE INDEX IF NOT EXISTS i_tr ON players(tr);
CREATE INDEX IF NOT EXISTS i_msgs ON msgs(al,id);
CREATE INDEX IF NOT EXISTS i_al ON players(al);

-- v2: Karten spenden, Geschenke, Spende-Limit
CREATE TABLE IF NOT EXISTS reqs(id INTEGER PRIMARY KEY AUTOINCREMENT, al TEXT NOT NULL, pid TEXT NOT NULL, card TEXT NOT NULL, need INTEGER NOT NULL, got INTEGER NOT NULL DEFAULT 0, ts INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS reqs_al ON reqs(al, ts);
CREATE TABLE IF NOT EXISTS gifts(id INTEGER PRIMARY KEY AUTOINCREMENT, pid TEXT NOT NULL, card TEXT NOT NULL, n INTEGER NOT NULL, src TEXT, ts INTEGER NOT NULL, done INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS gifts_pid ON gifts(pid, done);
CREATE TABLE IF NOT EXISTS dons(pid TEXT NOT NULL, ts INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS dons_pid ON dons(pid, ts);

-- v3: Freunde (Anfragen, Online-Status, Einladungen, Profil-Statistik)
ALTER TABLE players ADD COLUMN seen INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN st TEXT NOT NULL DEFAULT '{}';
CREATE TABLE IF NOT EXISTS freq(a TEXT NOT NULL, b TEXT NOT NULL, ts INTEGER NOT NULL, PRIMARY KEY(a,b));
CREATE INDEX IF NOT EXISTS freq_b ON freq(b);
CREATE TABLE IF NOT EXISTS invites(a TEXT NOT NULL, b TEXT NOT NULL, ts INTEGER NOT NULL, PRIMARY KEY(a,b));
CREATE INDEX IF NOT EXISTS inv_b ON invites(b);

-- v4: Ranglisten-Saison, Allianz-Rollen/Truhe/Krieg, Turnier, Push, Zuschauen
ALTER TABLE players ADD COLUMN rk INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE players ADD COLUMN rks TEXT NOT NULL DEFAULT '';
ALTER TABLE players ADD COLUMN rkb INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE players ADD COLUMN rkw INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN rkl INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN rlast TEXT NOT NULL DEFAULT '';
ALTER TABLE players ADD COLUMN ar INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN chr INTEGER NOT NULL DEFAULT 0;
ALTER TABLE alliances ADD COLUMN descr TEXT NOT NULL DEFAULT '';
ALTER TABLE alliances ADD COLUMN mintr INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS i_rk ON players(rks,rk);
CREATE INDEX IF NOT EXISTS i_chr ON players(chr);
CREATE TABLE IF NOT EXISTS acp(al TEXT NOT NULL, wk INTEGER NOT NULL, pid TEXT NOT NULL, n INTEGER NOT NULL DEFAULT 0, ts INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(al,wk,pid));
CREATE INDEX IF NOT EXISTS acp_wk ON acp(wk,al);
CREATE TABLE IF NOT EXISTS tour(wk INTEGER NOT NULL, pid TEXT NOT NULL, best INTEGER NOT NULL DEFAULT 0, ts INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(wk,pid));
CREATE INDEX IF NOT EXISTS tour_best ON tour(wk,best);
CREATE TABLE IF NOT EXISTS pushs(pid TEXT PRIMARY KEY, ep TEXT NOT NULL, p256 TEXT NOT NULL, auth TEXT NOT NULL, ts INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS kv(k TEXT PRIMARY KEY, v TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS tv(id INTEGER PRIMARY KEY AUTOINCREMENT, a TEXT, b TEXT, an TEXT, bn TEXT, rk INTEGER NOT NULL DEFAULT 0, w INTEGER NOT NULL DEFAULT 0, ts INTEGER NOT NULL, data TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS tv_ts ON tv(ts);
CREATE INDEX IF NOT EXISTS tv_a ON tv(a);

-- v5: Cloud-Speicher, Kampfstatistik
CREATE TABLE IF NOT EXISTS saves(pid TEXT PRIMARY KEY, data TEXT NOT NULL, ts INTEGER NOT NULL, sus INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS bstat(day INTEGER NOT NULL, card TEXT NOT NULL, mode TEXT NOT NULL, n INTEGER NOT NULL DEFAULT 0, w INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(day,card,mode));
CREATE TABLE IF NOT EXISTS bgames(day INTEGER NOT NULL, mode TEXT NOT NULL, n INTEGER NOT NULL DEFAULT 0, w INTEGER NOT NULL DEFAULT 0, dur INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(day,mode));
ALTER TABLE players ADD COLUMN lb INTEGER NOT NULL DEFAULT 0;
