// Festung von Kaltmark: Server (Cloudflare Worker + D1)
const J=(o,s=200)=>new Response(JSON.stringify(o),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const sha=async t=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t)))].map(x=>x.toString(16).padStart(2,'0')).join('');
const rid=()=>crypto.randomUUID().replace(/-/g,'').slice(0,12);
const NAME=/^[A-Za-z0-9ÄÖÜäöüß _-]{3,16}$/, CID=/^[a-z]{2,12}$/;
const ids=(a,n)=>Array.isArray(a)?a.filter(k=>typeof k=='string'&&CID.test(k)).slice(0,n):[];
const num=(v,lo,hi)=>Math.max(lo,Math.min(hi,Math.floor(Number(v))||0));
async function auth(env,b){if(!b||typeof b.id!='string'||typeof b.token!='string')return null;const r=await env.DB.prepare('SELECT * FROM players WHERE id=?').bind(b.id).first();return r&&r.th===await sha(b.token)?r:null}
const pub=r=>({id:r.id,name:r.name,tr:r.tr,lv:r.lv,deck:JSON.parse(r.deck||'[]'),fort:JSON.parse(r.fort||'[]'),on:Date.now()-(r.seen||0)<150000?1:0,seen:r.seen||0,st:(()=>{try{return JSON.parse(r.st||'{}')}catch(e){return {}}})()});
export default{async fetch(req,env){const u=new URL(req.url);if(!u.pathname.startsWith('/api/'))return env.ASSETS.fetch(req);
 try{return await api(req,env,u)}catch(e){return J({error:'Serverfehler'},500)}}};
async function api(req,env,u){const p=u.pathname.slice(5),DB=env.DB;let b={};if(req.method=='POST'){try{b=await req.json()}catch(e){return J({error:'Ungültige Anfrage'},400)}}
 if(p=='ping')return J({ok:1});
 if(p=='register'){const name=String(b.name||'').trim();if(!NAME.test(name))return J({error:'Name: 3 bis 16 Zeichen (Buchstaben, Zahlen, Leerzeichen)'},400);const id=rid(),token=crypto.randomUUID();
  try{await DB.prepare('INSERT INTO players(id,name,lname,th,ts) VALUES(?,?,?,?,?)').bind(id,name,name.toLowerCase(),await sha(token),Date.now()).run()}catch(e){return J({error:'Der Name ist schon vergeben'},409)}return J({id,token,name})}
 if(p=='player'){const r=await DB.prepare('SELECT * FROM players WHERE id=?').bind(String(u.searchParams.get('id')||'')).first();if(!r)return J({error:'Nicht gefunden'},404);return J({player:pub(r)})}
 if(p=='top'){const r=await DB.prepare('SELECT id,name,tr,lv FROM players ORDER BY tr DESC LIMIT 20').all();return J({top:r.results})}
 if(p=='search'){const q=String(u.searchParams.get('q')||'').trim().toLowerCase().replace(/[%_]/g,'');if(q.length<2)return J({players:[]});const r=await DB.prepare('SELECT id,name,tr,lv FROM players WHERE lname LIKE ? ORDER BY tr DESC LIMIT 10').bind(q+'%').all();return J({players:r.results})}
 if(p=='alliances'){const r=await DB.prepare('SELECT a.id,a.name,(SELECT COUNT(*) FROM players WHERE al=a.id) AS n FROM alliances a ORDER BY n DESC,a.ts DESC LIMIT 30').all();return J({alliances:r.results})}
 if(p=='live'){if(req.headers.get('Upgrade')!=='websocket')return J({error:'WebSocket nötig'},426);const me=await auth(env,{id:u.searchParams.get('id')||'',token:u.searchParams.get('token')||''});if(!me)return J({error:'Nicht angemeldet'},401);
  const nu=new URL(req.url);nu.searchParams.delete('token');nu.searchParams.set('pid',me.id);nu.searchParams.set('name',me.name);return env.LOBBY.get(env.LOBBY.idFromName('main')).fetch(new Request(nu.toString(),req))}
 const me=await auth(env,b);if(!me)return J({error:'Nicht angemeldet'},401);
 if(p=='me')return J({id:me.id,name:me.name,tr:me.tr,lv:me.lv,al:me.al});
 if(p=='sync'){if(b.st&&typeof b.st=='object'){const q=b.st,o={w:num(q.w,0,1e6),l:num(q.l,0,1e6),best:num(q.best,0,99999),lw:num(q.lw,0,1e6),cr:num(q.cr,0,1e7),fav:typeof q.fav=='string'&&CID.test(q.fav)?q.fav:''};await DB.prepare('UPDATE players SET st=? WHERE id=?').bind(JSON.stringify(o),me.id).run()}const now=Date.now(),mins=Math.max(0,(now-(me.ts||now))/6e4),first=!me.deck||me.deck=='[]',maxTr=first?99999:(me.tr||0)+35+Math.ceil(mins/2)*35,maxLv=first?999:(me.lv||1)+1+Math.ceil(mins/10);await DB.prepare('UPDATE players SET tr=?,lv=?,deck=?,fort=?,ts=? WHERE id=?').bind(Math.min(num(b.tr,0,99999),maxTr),Math.min(num(b.lv,1,999),maxLv),JSON.stringify(ids(b.deck,8)),JSON.stringify((Array.isArray(b.fort)?b.fort.slice(0,3):[]).map(k=>typeof k=='string'&&CID.test(k)?k:'')),Date.now(),me.id).run();return J({ok:1})}
 if(p=='arena'){const t=num(b.tr,0,99999),r=await DB.prepare("SELECT * FROM players WHERE id!=? AND deck!='[]' ORDER BY ABS(tr-?),ts DESC LIMIT 5").bind(me.id,t).all();if(!r.results.length)return J({opp:null});return J({opp:pub(r.results[Math.floor(Math.random()*r.results.length)])})}
 if(p=='friends'){const r=await DB.prepare('SELECT p.* FROM friends f JOIN players p ON p.id=f.b WHERE f.a=? LIMIT 100').bind(me.id).all();const q=await DB.prepare('SELECT p.id,p.name,p.tr,p.lv FROM freq f JOIN players p ON p.id=f.a WHERE f.b=? ORDER BY f.ts DESC LIMIT 30').bind(me.id).all();const o=await DB.prepare('SELECT b FROM freq WHERE a=?').bind(me.id).all();return J({friends:r.results.map(pub).sort((x,y)=>y.on-x.on||y.tr-x.tr),reqs:q.results,sent:o.results.map(x=>x.b)})}
 if(p=='seen'){const now=Date.now();await DB.prepare('UPDATE players SET seen=? WHERE id=?').bind(now,me.id).run();const inv=await DB.prepare('SELECT i.a AS id,p.name FROM invites i JOIN players p ON p.id=i.a WHERE i.b=? AND i.ts>?').bind(me.id,now-60000).all();const rq=await DB.prepare('SELECT COUNT(*) AS n FROM freq WHERE b=?').bind(me.id).first();return J({inv:inv.results,reqs:rq.n})}
 if(p=='friend/accept'||p=='friend/decline'){const f=String(b.friend||'');const x=await DB.prepare('SELECT a FROM freq WHERE a=? AND b=?').bind(f,me.id).first();if(!x)return J({error:'Keine Anfrage'},404);const ops=[DB.prepare('DELETE FROM freq WHERE a=? AND b=?').bind(f,me.id)];if(p=='friend/accept')ops.push(DB.prepare('INSERT OR IGNORE INTO friends(a,b) VALUES(?,?)').bind(me.id,f),DB.prepare('INSERT OR IGNORE INTO friends(a,b) VALUES(?,?)').bind(f,me.id));await DB.batch(ops);return J({ok:1})}
 if(p=='invite'){const f=String(b.friend||'');const x=await DB.prepare('SELECT a FROM friends WHERE a=? AND b=?').bind(me.id,f).first();if(!x)return J({error:'Nur Freunde einladen'},400);await DB.prepare('INSERT OR REPLACE INTO invites(a,b,ts) VALUES(?,?,?)').bind(me.id,f,Date.now()).run();return J({ok:1})}
 if(p=='invite/answer'){await DB.prepare('DELETE FROM invites WHERE a=? AND b=?').bind(String(b.friend||''),me.id).run();return J({ok:1})}
 if(p=='friend/add'){const f=String(b.friend||'');if(f==me.id)return J({error:'Das bist du selbst'},400);const x=await DB.prepare('SELECT id FROM players WHERE id=?').bind(f).first();if(!x)return J({error:'Spieler nicht gefunden'},404);
  const already=await DB.prepare('SELECT a FROM friends WHERE a=? AND b=?').bind(me.id,f).first();if(already)return J({ok:1,already:1});
  const back=await DB.prepare('SELECT a FROM freq WHERE a=? AND b=?').bind(f,me.id).first();if(back){await DB.batch([DB.prepare('DELETE FROM freq WHERE a=? AND b=?').bind(f,me.id),DB.prepare('INSERT OR IGNORE INTO friends(a,b) VALUES(?,?)').bind(me.id,f),DB.prepare('INSERT OR IGNORE INTO friends(a,b) VALUES(?,?)').bind(f,me.id)]);return J({ok:1,mutual:1})}
  await DB.prepare('INSERT OR REPLACE INTO freq(a,b,ts) VALUES(?,?,?)').bind(me.id,f,Date.now()).run();return J({ok:1,sent:1})}
 if(p=='friend/remove'){const f=String(b.friend||'');await DB.batch([DB.prepare('DELETE FROM friends WHERE (a=? AND b=?) OR (a=? AND b=?)').bind(me.id,f,f,me.id),DB.prepare('DELETE FROM freq WHERE (a=? AND b=?) OR (a=? AND b=?)').bind(me.id,f,f,me.id)]);return J({ok:1})}
 if(p=='alliance/create'){const name=String(b.name||'').trim();if(!NAME.test(name))return J({error:'Name: 3 bis 16 Zeichen'},400);const id=rid();try{await DB.prepare('INSERT INTO alliances(id,name,lname,owner,ts) VALUES(?,?,?,?,?)').bind(id,name,name.toLowerCase(),me.id,Date.now()).run()}catch(e){return J({error:'Der Name ist schon vergeben'},409)}await DB.prepare('UPDATE players SET al=? WHERE id=?').bind(id,me.id).run();return J({ok:1,al:id})}
 if(p=='alliance/join'){const a=await DB.prepare('SELECT id FROM alliances WHERE id=?').bind(String(b.alliance||'')).first();if(!a)return J({error:'Allianz nicht gefunden'},404);const n=await DB.prepare('SELECT COUNT(*) AS n FROM players WHERE al=?').bind(a.id).first();if(n.n>=50)return J({error:'Die Allianz ist voll'},400);await DB.prepare('UPDATE players SET al=? WHERE id=?').bind(a.id,me.id).run();return J({ok:1,al:a.id})}
 if(p=='alliance/leave'){await DB.prepare('UPDATE players SET al=NULL WHERE id=?').bind(me.id).run();return J({ok:1})}
 if(p=='alliance/info'){if(!me.al)return J({alliance:null});const a=await DB.prepare('SELECT id,name FROM alliances WHERE id=?').bind(me.al).first();if(!a){await DB.prepare('UPDATE players SET al=NULL WHERE id=?').bind(me.id).run();return J({alliance:null})}
  const m=await DB.prepare('SELECT id,name,tr,lv FROM players WHERE al=? ORDER BY tr DESC LIMIT 50').bind(a.id).all(),c=await DB.prepare('SELECT m.id,p.name,m.t,m.ts FROM msgs m JOIN players p ON p.id=m.pid WHERE m.al=? ORDER BY m.id DESC LIMIT 30').bind(a.id).all();return J({alliance:a,members:m.results,msgs:c.results.reverse()})}
 if(p=='alliance/msg'){if(!me.al)return J({error:'Keine Allianz'},400);const t=String(b.text||'').trim().slice(0,140);if(!t)return J({error:'Leer'},400);const last=await DB.prepare('SELECT ts FROM msgs WHERE pid=? ORDER BY id DESC LIMIT 1').bind(me.id).first();if(last&&Date.now()-last.ts<1000)return J({error:'Zu schnell'},429);await DB.prepare('INSERT INTO msgs(al,pid,t,ts) VALUES(?,?,?,?)').bind(me.al,me.id,t,Date.now()).run();return J({ok:1})}

 if(p=='delete'){await DB.batch([DB.prepare('DELETE FROM msgs WHERE pid=?').bind(me.id),DB.prepare('DELETE FROM friends WHERE a=? OR b=?').bind(me.id,me.id),DB.prepare('DELETE FROM reqs WHERE pid=?').bind(me.id),DB.prepare('DELETE FROM gifts WHERE pid=?').bind(me.id),DB.prepare('DELETE FROM dons WHERE pid=?').bind(me.id),DB.prepare('DELETE FROM freq WHERE a=? OR b=?').bind(me.id,me.id),DB.prepare('DELETE FROM invites WHERE a=? OR b=?').bind(me.id,me.id),DB.prepare('DELETE FROM players WHERE id=?').bind(me.id)]);
  if(me.al){const n=await DB.prepare('SELECT COUNT(*) AS n FROM players WHERE al=?').bind(me.al).first();if(!n.n)await DB.batch([DB.prepare('DELETE FROM alliances WHERE id=?').bind(me.al),DB.prepare('DELETE FROM msgs WHERE al=?').bind(me.al),DB.prepare('DELETE FROM reqs WHERE al=?').bind(me.al)])}return J({ok:1})}
 if(p=='alliance/request'){if(!me.al)return J({error:'Keine Allianz'},400);const card=String(b.card||'');if(!CID.test(card))return J({error:'Ungültige Karte'},400);const last=await DB.prepare('SELECT ts FROM reqs WHERE pid=? ORDER BY id DESC LIMIT 1').bind(me.id).first();if(last&&Date.now()-last.ts<8*36e5)return J({error:'Nur alle 8 Stunden eine Anfrage'},429);
  await DB.prepare('INSERT INTO reqs(al,pid,card,need,got,ts) VALUES(?,?,?,?,0,?)').bind(me.al,me.id,card,num(b.need,1,10),Date.now()).run();return J({ok:1})}
 if(p=='alliance/requests'){if(!me.al)return J({reqs:[]});const r=await DB.prepare('SELECT r.id,r.pid,p.name,r.card,r.need,r.got,r.ts FROM reqs r JOIN players p ON p.id=r.pid WHERE r.al=? AND r.got<r.need AND r.ts>? ORDER BY r.id DESC LIMIT 30').bind(me.al,Date.now()-864e5).all();return J({reqs:r.results})}
 if(p=='alliance/donate'){const q=await DB.prepare('SELECT * FROM reqs WHERE id=?').bind(num(b.req,0,1e12)).first();if(!q||q.al!==me.al)return J({error:'Anfrage nicht gefunden'},404);if(q.pid===me.id)return J({error:'Eigene Anfrage'},400);if(q.got>=q.need)return J({error:'Schon erfüllt'},400);
  const d=await DB.prepare('SELECT COUNT(*) AS n FROM dons WHERE pid=? AND ts>?').bind(me.id,Date.now()-864e5).first();if(d.n>=30)return J({error:'Tageslimit für Spenden erreicht'},429);
  await DB.batch([DB.prepare('UPDATE reqs SET got=got+1 WHERE id=? AND got<need').bind(q.id),DB.prepare('INSERT INTO gifts(pid,card,n,src,ts) VALUES(?,?,1,?,?)').bind(q.pid,q.card,me.name,Date.now()),DB.prepare('INSERT INTO dons(pid,ts) VALUES(?,?)').bind(me.id,Date.now())]);return J({ok:1})}
 if(p=='gifts'){const r=await DB.prepare('SELECT id,card,n,src FROM gifts WHERE pid=? AND done=0 LIMIT 50').bind(me.id).all();if(r.results.length)await DB.prepare('UPDATE gifts SET done=1 WHERE pid=? AND done=0 AND id<=?').bind(me.id,Math.max(...r.results.map(g=>g.id))).run();return J({gifts:r.results})}
 return J({error:'Unbekannt'},404)}

// Live-Kämpfe: Durable Object als Lobby + Weiterleitung (WebSocket Hibernation)
export class Lobby{constructor(state,env){this.state=state}
 async fetch(req){const u=new URL(req.url);if(req.headers.get('Upgrade')!=='websocket')return new Response('WebSocket nötig',{status:426});const pid=u.searchParams.get('pid')||'',name=u.searchParams.get('name')||'Spieler';
  for(const w of this.state.getWebSockets(pid)){try{w.close(4000,'ersetzt')}catch(e){}}
  const pair=new WebSocketPair(),[c,s]=Object.values(pair);this.state.acceptWebSocket(s,[pid]);s.serializeAttachment({pid,name,st:'idle'});return new Response(null,{status:101,webSocket:c})}
 partner(a){if(!a||!a.partner)return null;for(const p of this.state.getWebSockets(a.partner)){const b=p.deserializeAttachment();if(b&&b.mid===a.mid)return p}return null}
 webSocketMessage(ws,msg){let m;try{m=JSON.parse(typeof msg==='string'?msg:new TextDecoder().decode(msg))}catch(e){return}const a=ws.deserializeAttachment()||{};
  if(m.t==='find'){a.st='wait';a.code=String(m.code||'').slice(0,40);a.info=m.info||{};a.info.name=a.name;a.since=Date.now();ws.serializeAttachment(a);
   let best=null,bd=1e9;for(const o of this.state.getWebSockets()){if(o===ws)continue;const b=o.deserializeAttachment();if(!b||b.st!=='wait'||b.pid===a.pid||(b.code||'')!==a.code)continue;const d=Math.abs(((b.info||{}).tr||0)-((a.info||{}).tr||0));if(d<bd){bd=d;best=o}}
   if(best){const b=best.deserializeAttachment(),mid=Math.random().toString(36).slice(2,10);b.st='play';b.partner=a.pid;b.mid=mid;a.st='play';a.partner=b.pid;a.mid=mid;best.serializeAttachment(b);ws.serializeAttachment(a);
    try{best.send(JSON.stringify({t:'start',role:'host',mid,opp:a.info}));ws.send(JSON.stringify({t:'start',role:'guest',mid,opp:b.info}))}catch(e){}return}
   try{ws.send(JSON.stringify({t:'wait'}))}catch(e){}return}
  if(m.t==='cancel'){a.st='idle';ws.serializeAttachment(a);return}
  if(m.t==='ping'){try{ws.send('{"t":"pong"}')}catch(e){}return}
  if(a.st==='play'){const p=this.partner(a);if(!p){try{ws.send('{"t":"left"}')}catch(e){}a.st='idle';ws.serializeAttachment(a);return}
   try{p.send(typeof msg==='string'?msg:JSON.stringify(m))}catch(e){}
   if(m.t==='end'||m.t==='bye'){a.st='idle';ws.serializeAttachment(a);const b=p.deserializeAttachment();b.st='idle';p.serializeAttachment(b)}}}
 webSocketClose(ws){const a=ws.deserializeAttachment();if(a&&a.st==='play'){const p=this.partner(a);if(p){try{p.send('{"t":"left"}')}catch(e){}const b=p.deserializeAttachment();b.st='idle';p.serializeAttachment(b)}}}
 webSocketError(ws){this.webSocketClose(ws)}}
