// Festung von Kaltmark: Server (Cloudflare Worker + D1)
const J=(o,s=200)=>new Response(JSON.stringify(o),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const sha=async t=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t)))].map(x=>x.toString(16).padStart(2,'0')).join('');
const rid=()=>crypto.randomUUID().replace(/-/g,'').slice(0,12);
const NAME=/^[A-Za-z0-9ÄÖÜäöüß _-]{3,16}$/, CID=/^[a-z]{2,12}$/;
const ids=(a,n)=>Array.isArray(a)?a.filter(k=>typeof k=='string'&&CID.test(k)).slice(0,n):[];
const num=(v,lo,hi)=>Math.max(lo,Math.min(hi,Math.floor(Number(v))||0));
async function auth(env,b){if(!b||typeof b.id!='string'||typeof b.token!='string')return null;const r=await env.DB.prepare('SELECT * FROM players WHERE id=?').bind(b.id).first();return r&&r.th===await sha(b.token)?r:null}
const pub=r=>({id:r.id,name:r.name,tr:r.tr,lv:r.lv,deck:JSON.parse(r.deck||'[]'),fort:JSON.parse(r.fort||'[]')});
export default{async fetch(req,env){const u=new URL(req.url);if(!u.pathname.startsWith('/api/'))return env.ASSETS.fetch(req);
 try{return await api(req,env,u)}catch(e){return J({error:'Serverfehler'},500)}}};
async function api(req,env,u){const p=u.pathname.slice(5),DB=env.DB;let b={};if(req.method=='POST'){try{b=await req.json()}catch(e){return J({error:'Ungültige Anfrage'},400)}}
 if(p=='ping')return J({ok:1});
 if(p=='register'){const name=String(b.name||'').trim();if(!NAME.test(name))return J({error:'Name: 3 bis 16 Zeichen (Buchstaben, Zahlen, Leerzeichen)'},400);const id=rid(),token=crypto.randomUUID();
  try{await DB.prepare('INSERT INTO players(id,name,lname,th,ts) VALUES(?,?,?,?,?)').bind(id,name,name.toLowerCase(),await sha(token),Date.now()).run()}catch(e){return J({error:'Der Name ist schon vergeben'},409)}return J({id,token,name})}
 if(p=='top'){const r=await DB.prepare('SELECT id,name,tr,lv FROM players ORDER BY tr DESC LIMIT 20').all();return J({top:r.results})}
 if(p=='search'){const q=String(u.searchParams.get('q')||'').trim().toLowerCase().replace(/[%_]/g,'');if(q.length<2)return J({players:[]});const r=await DB.prepare('SELECT id,name,tr,lv FROM players WHERE lname LIKE ? ORDER BY tr DESC LIMIT 10').bind(q+'%').all();return J({players:r.results})}
 if(p=='alliances'){const r=await DB.prepare('SELECT a.id,a.name,(SELECT COUNT(*) FROM players WHERE al=a.id) AS n FROM alliances a ORDER BY n DESC,a.ts DESC LIMIT 30').all();return J({alliances:r.results})}
 const me=await auth(env,b);if(!me)return J({error:'Nicht angemeldet'},401);
 if(p=='me')return J({id:me.id,name:me.name,tr:me.tr,lv:me.lv,al:me.al});
 if(p=='sync'){const now=Date.now(),mins=Math.max(0,(now-(me.ts||now))/6e4),first=!me.deck||me.deck=='[]',maxTr=first?99999:(me.tr||0)+35+Math.ceil(mins/2)*35,maxLv=first?999:(me.lv||1)+1+Math.ceil(mins/10);await DB.prepare('UPDATE players SET tr=?,lv=?,deck=?,fort=?,ts=? WHERE id=?').bind(Math.min(num(b.tr,0,99999),maxTr),Math.min(num(b.lv,1,999),maxLv),JSON.stringify(ids(b.deck,8)),JSON.stringify((Array.isArray(b.fort)?b.fort.slice(0,3):[]).map(k=>typeof k=='string'&&CID.test(k)?k:'')),Date.now(),me.id).run();return J({ok:1})}
 if(p=='arena'){const t=num(b.tr,0,99999),r=await DB.prepare("SELECT * FROM players WHERE id!=? AND deck!='[]' ORDER BY ABS(tr-?),ts DESC LIMIT 5").bind(me.id,t).all();if(!r.results.length)return J({opp:null});return J({opp:pub(r.results[Math.floor(Math.random()*r.results.length)])})}
 if(p=='friends'){const r=await DB.prepare('SELECT p.* FROM friends f JOIN players p ON p.id=f.b WHERE f.a=? LIMIT 50').bind(me.id).all();return J({friends:r.results.map(pub)})}
 if(p=='friend/add'){const f=String(b.friend||'');if(f==me.id)return J({error:'Das bist du selbst'},400);const x=await DB.prepare('SELECT id FROM players WHERE id=?').bind(f).first();if(!x)return J({error:'Spieler nicht gefunden'},404);await DB.prepare('INSERT OR IGNORE INTO friends(a,b) VALUES(?,?)').bind(me.id,f).run();return J({ok:1})}
 if(p=='friend/remove'){await DB.prepare('DELETE FROM friends WHERE a=? AND b=?').bind(me.id,String(b.friend||'')).run();return J({ok:1})}
 if(p=='alliance/create'){const name=String(b.name||'').trim();if(!NAME.test(name))return J({error:'Name: 3 bis 16 Zeichen'},400);const id=rid();try{await DB.prepare('INSERT INTO alliances(id,name,lname,owner,ts) VALUES(?,?,?,?,?)').bind(id,name,name.toLowerCase(),me.id,Date.now()).run()}catch(e){return J({error:'Der Name ist schon vergeben'},409)}await DB.prepare('UPDATE players SET al=? WHERE id=?').bind(id,me.id).run();return J({ok:1,al:id})}
 if(p=='alliance/join'){const a=await DB.prepare('SELECT id FROM alliances WHERE id=?').bind(String(b.alliance||'')).first();if(!a)return J({error:'Allianz nicht gefunden'},404);const n=await DB.prepare('SELECT COUNT(*) AS n FROM players WHERE al=?').bind(a.id).first();if(n.n>=50)return J({error:'Die Allianz ist voll'},400);await DB.prepare('UPDATE players SET al=? WHERE id=?').bind(a.id,me.id).run();return J({ok:1,al:a.id})}
 if(p=='alliance/leave'){await DB.prepare('UPDATE players SET al=NULL WHERE id=?').bind(me.id).run();return J({ok:1})}
 if(p=='alliance/info'){if(!me.al)return J({alliance:null});const a=await DB.prepare('SELECT id,name FROM alliances WHERE id=?').bind(me.al).first();if(!a){await DB.prepare('UPDATE players SET al=NULL WHERE id=?').bind(me.id).run();return J({alliance:null})}
  const m=await DB.prepare('SELECT id,name,tr,lv FROM players WHERE al=? ORDER BY tr DESC LIMIT 50').bind(a.id).all(),c=await DB.prepare('SELECT m.id,p.name,m.t,m.ts FROM msgs m JOIN players p ON p.id=m.pid WHERE m.al=? ORDER BY m.id DESC LIMIT 30').bind(a.id).all();return J({alliance:a,members:m.results,msgs:c.results.reverse()})}
 if(p=='alliance/msg'){if(!me.al)return J({error:'Keine Allianz'},400);const t=String(b.text||'').trim().slice(0,140);if(!t)return J({error:'Leer'},400);const last=await DB.prepare('SELECT ts FROM msgs WHERE pid=? ORDER BY id DESC LIMIT 1').bind(me.id).first();if(last&&Date.now()-last.ts<1000)return J({error:'Zu schnell'},429);await DB.prepare('INSERT INTO msgs(al,pid,t,ts) VALUES(?,?,?,?)').bind(me.al,me.id,t,Date.now()).run();return J({ok:1})}

 if(p=='delete'){await DB.batch([DB.prepare('DELETE FROM msgs WHERE pid=?').bind(me.id),DB.prepare('DELETE FROM friends WHERE a=? OR b=?').bind(me.id,me.id),DB.prepare('DELETE FROM reqs WHERE pid=?').bind(me.id),DB.prepare('DELETE FROM gifts WHERE pid=?').bind(me.id),DB.prepare('DELETE FROM dons WHERE pid=?').bind(me.id),DB.prepare('DELETE FROM players WHERE id=?').bind(me.id)]);
  if(me.al){const n=await DB.prepare('SELECT COUNT(*) AS n FROM players WHERE al=?').bind(me.al).first();if(!n.n)await DB.batch([DB.prepare('DELETE FROM alliances WHERE id=?').bind(me.al),DB.prepare('DELETE FROM msgs WHERE al=?').bind(me.al),DB.prepare('DELETE FROM reqs WHERE al=?').bind(me.al)])}return J({ok:1})}
 if(p=='alliance/request'){if(!me.al)return J({error:'Keine Allianz'},400);const card=String(b.card||'');if(!CID.test(card))return J({error:'Ungültige Karte'},400);const last=await DB.prepare('SELECT ts FROM reqs WHERE pid=? ORDER BY id DESC LIMIT 1').bind(me.id).first();if(last&&Date.now()-last.ts<8*36e5)return J({error:'Nur alle 8 Stunden eine Anfrage'},429);
  await DB.prepare('INSERT INTO reqs(al,pid,card,need,got,ts) VALUES(?,?,?,?,0,?)').bind(me.al,me.id,card,num(b.need,1,10),Date.now()).run();return J({ok:1})}
 if(p=='alliance/requests'){if(!me.al)return J({reqs:[]});const r=await DB.prepare('SELECT r.id,r.pid,p.name,r.card,r.need,r.got,r.ts FROM reqs r JOIN players p ON p.id=r.pid WHERE r.al=? AND r.got<r.need AND r.ts>? ORDER BY r.id DESC LIMIT 30').bind(me.al,Date.now()-864e5).all();return J({reqs:r.results})}
 if(p=='alliance/donate'){const q=await DB.prepare('SELECT * FROM reqs WHERE id=?').bind(num(b.req,0,1e12)).first();if(!q||q.al!==me.al)return J({error:'Anfrage nicht gefunden'},404);if(q.pid===me.id)return J({error:'Eigene Anfrage'},400);if(q.got>=q.need)return J({error:'Schon erfüllt'},400);
  const d=await DB.prepare('SELECT COUNT(*) AS n FROM dons WHERE pid=? AND ts>?').bind(me.id,Date.now()-864e5).first();if(d.n>=30)return J({error:'Tageslimit für Spenden erreicht'},429);
  await DB.batch([DB.prepare('UPDATE reqs SET got=got+1 WHERE id=? AND got<need').bind(q.id),DB.prepare('INSERT INTO gifts(pid,card,n,src,ts) VALUES(?,?,1,?,?)').bind(q.pid,q.card,me.name,Date.now()),DB.prepare('INSERT INTO dons(pid,ts) VALUES(?,?)').bind(me.id,Date.now())]);return J({ok:1})}
 if(p=='gifts'){const r=await DB.prepare('SELECT id,card,n,src FROM gifts WHERE pid=? AND done=0 LIMIT 50').bind(me.id).all();if(r.results.length)await DB.prepare('UPDATE gifts SET done=1 WHERE pid=? AND done=0 AND id<=?').bind(me.id,Math.max(...r.results.map(g=>g.id))).run();return J({gifts:r.results})}
 return J({error:'Unbekannt'},404)}
